### ISSUE TITLE
Fatal error: drv_types.h: No such file or directory

### ISSUE THREAD

**Issue by JosemaGIT** [lwfinger/rtw8852be#61]
I am trying to compile the rtw8852be drives and I get the following errors. I get that the make command is not able to recognise the headers file in the "include" directory but I do not understand why or how to solve it.

This is the output of trying to use make.

> #rm -f .symvers.8852be
> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.15.4-arch2-1/build M=/home/josema/Downloads/Repos/rtw8852be  modules
> make[1]: Entering directory '/usr/lib/modules/6.15.4-arch2-1/build'
> make[2]: Entering directory '/home/josema/Downloads/Repos/rtw8852be'
>   CC [M]  platform/platform_linux_pc_pci.o
> platform/platform_linux_pc_pci.c:15:10: fatal error: drv_types.h: No such file or directory
>    15 | #include "drv_types.h"
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[4]: *** [/usr/lib/modules/6.15.4-arch2-1/build/scripts/Makefile.build:203: platform/platform_linux_pc_pci.o] Error 1
> make[3]: *** [/usr/lib/modules/6.15.4-arch2-1/build/Makefile:2003: .] Error 2
> make[2]: *** [/usr/lib/modules/6.15.4-arch2-1/build/Makefile:248: __sub-make] Error 2
> make[2]: Leaving directory '/home/josema/Downloads/Repos/rtw8852be'
> make[1]: *** [Makefile:248: __sub-make] Error 2
> make[1]: Leaving directory '/usr/lib/modules/6.15.4-arch2-1/build'
> make: *** [Makefile:635: modules] Error 2

**Comment by faheemezani** [comment]
I am also encountering the same problem on my Fedora 42. The following error was encountered when I ran a `make`:

```
$ make
#rm -f .symvers.8852be
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.15.7-200.fc42.x86_64/build M=/home/faheem/Drivers/rtw8852be/rtw8852be  modules
make[1]: Entering directory '/usr/src/kernels/6.15.7-200.fc42.x86_64'
make[2]: Entering directory '/home/faheem/Drivers/rtw8852be/rtw8852be'
  CC [M]  platform/platform_linux_pc_pci.o
platform/platform_linux_pc_pci.c:15:10: fatal error: drv_types.h: No such file or directory
   15 | #include "drv_types.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/kernels/6.15.7-200.fc42.x86_64/scripts/Makefile.build:203: platform/platform_linux_pc_pci.o] Error 1
make[3]: *** [/usr/src/kernels/6.15.7-200.fc42.x86_64/Makefile:2043: .] Error 2
make[2]: *** [/usr/src/kernels/6.15.7-200.fc42.x86_64/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/home/faheem/Drivers/rtw8852be/rtw8852be'
make[1]: *** [Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.15.7-200.fc42.x86_64'
make: *** [Makefile:635: modules] Error 2
```
Other context you might want to know:
- Operating system and version: Fedora 42
- Kernel version: 6.15.7-200.fc42.x86_64
- All build essentials have been downloaded and installed

**Comment by gt9696** [comment]
my wifi and bluetooth are missing. wish you find the following terminal log useful.

> cd rtw8852be
> make
> sudo make install
> Cloning into 'rtw8852be'...
> remote: Enumerating objects: 9555, done.
> remote: Counting objects: 100% (278/278), done.
> remote: Compressing objects: 100% (113/113), done.
> remote: Total 9555 (delta 191), reused 204 (delta 165), pack-reused 9277 (from 1)
> Receiving objects: 100% (9555/9555), 20.99 MiB | 17.10 MiB/s, done.
> Resolving deltas: 100% (6160/6160), done.
> #rm -f .symvers.8852be
> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.15.10-200.fc42.x86_64/build M=/home/***/rtw8852be  modules
> make[1]: Entering directory '/usr/src/kernels/6.15.10-200.fc42.x86_64'
> make[2]: Entering directory '/home/***/rtw8852be'
>   CC [M]  platform/platform_linux_pc_pci.o
> platform/platform_linux_pc_pci.c:15:10: fatal error: drv_types.h: No such file or directory
>    15 | #include "drv_types.h"
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[4]: *** [/usr/src/kernels/6.15.10-200.fc42.x86_64/scripts/Makefile.build:203: platform/platform_linux_pc_pci.o] Error 1
> make[3]: *** [/usr/src/kernels/6.15.10-200.fc42.x86_64/Makefile:2043: .] Error 2
> make[2]: *** [/usr/src/kernels/6.15.10-200.fc42.x86_64/Makefile:260: __sub-make] Error 2
> make[2]: Leaving directory '/home/***/rtw8852be'
> make[1]: *** [Makefile:260: __sub-make] Error 2
> make[1]: Leaving directory '/usr/src/kernels/6.15.10-200.fc42.x86_64'
> make: *** [Makefile:635: modules] Error 2
> install -p -m 644 8852be.ko  /lib/modules/6.15.10-200.fc42.x86_64/kernel/drivers/net/wireless/
> install: cannot stat '8852be.ko': No such file or directory
> make: *** [Makefile:644: install] Error 1

**Comment by MayaChen350** [comment]
Same here.

While we wait for a solution, can I ask what you guys use instead?

**Comment by MyouKin** [comment]
@faheemezani @JosemaGIT @MayaChen350 @gt9696 Hi everyone, this issue is caused by changes in newer Linux kernels. I’ve fixed the compatibility issues, and the driver now works on my Ubuntu 24.04 laptop. I’ve also opened a PR. You can find the updated code in [[my fork](https://github.com/MyouKin/rtw8852be)](https://github.com/MyouKin/rtw8852be).

**Comment by MayaChen350** [comment]
Wow, I didn't expect to see an update on this, I ended up changing the wifi card in my laptop last year 💔 

Still, thank you for the fix!

**Comment by MyouKin** [comment]
Kernel-related driver issues can be a real headache. I actually fixed this yesterday while sorting out some driver problems on my new work laptop running Ubuntu. Hope this helps anyone else running into the same thing!🥰
